services:
    app:
        build:
            context: .
        container_name: app
        extra_hosts:
          - "host.docker.internal:host-gateway"
        volumes:
            - .:/var/www/html
        ports:
            - ${PHP_FPM_PORT:-9000}:9000
        networks:
            - laravel_network
        depends_on:
            - postgres

    postgres:
        container_name: postgres
        image: postgres:15-alpine
        environment:
            POSTGRES_DB: ${DB_DATABASE:-laravel}
            POSTGRES_USER: ${DB_USERNAME:-laravel}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - laravel_network

    nginx:
        container_name: nginx
        image: nginx:alpine
        volumes:
            - .:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - ${APP_PORT:-8000}:8000
        depends_on:
            - app
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge

volumes:
    postgres_data:
        driver: local